"""create workspace table

Revision ID: 5a9228f86ae9
Revises: a09b863dc465
Create Date: 2026-07-30 12:12:55.623987
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a9228f86ae9'
down_revision: Union[str, None] = 'a09b863dc465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('GENERAL', 'PROJECT', name='workspacetype'), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspaces')
    # ### end Alembic commands ###
