"""add workspace to documents

Revision ID: a60309795f94
Revises: 5a9228f86ae9
Create Date: 2026-07-30 20:45:32.906670
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a60309795f94'
down_revision: Union[str, None] = '5a9228f86ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'workspace_id')
    