"""add workspace to todos

Revision ID: f5a6429d9bb8
Revises: fb60c073b291
Create Date: 2026-07-31 01:02:07.714075
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f5a6429d9bb8'
down_revision: Union[str, None] = 'fb60c073b291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'todos', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'workspace_id')
    # ### end Alembic commands ###
