"""add workspace to notes

Revision ID: fb60c073b291
Revises: a60309795f94
Create Date: 2026-07-31 00:40:56.678728
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb60c073b291'
down_revision: Union[str, None] = 'a60309795f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'notes', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'workspace_id')
    # ### end Alembic commands ###
